Unique pragma for sqlite & postgre
moigagoo/norm pull request #91
Opened 2020-10-24 14:44 UTC by Clonkk

* Added unique pragma

2020-10-24 19:21 UTC, moigagoo requested changes
@Clonkk this looks pretty obvious but it's hard to see how that pragma affects the way queries are generated and what's the profit of using it for the user. This should be addressed in tests.

Also, please add a changelog entry for this change.

2020-10-24 19:21 UTC, moigagoo commented on src/norm/pragmas.nim
> +template unique* {.pragma.}
@Clonkk this needs a docstring.

2020-10-25 11:09 UTC, moigagoo requested changes
Please add a test and resolve the conflict in the changelog.

2020-10-25 19:19 UTC, moigagoo requested changes

2020-10-25 19:19 UTC, moigagoo commented on changelog.rst
> +-   [+] Added a define to enable logging
This line is redundant, see the line below.

2020-10-25 19:19 UTC, moigagoo commented on src/norm/pragmas.nim
> +##[ Mark field  as unique
This should be a single line comment.

2020-10-25 19:19 UTC, moigagoo commented on tests/tpostgresunique.nim
> +proc duplicateInsert(dbConn: DbConn)
What's the purpose of this forward declaration?

2020-10-25 19:19 UTC, moigagoo commented on tests/tpostgresunique.nim
> +proc duplicateInsert(dbConn: DbConn)=
I think this is way overcomplicated. You could just have all that as part of the test, inside the test body.

2020-10-25 19:19 UTC, moigagoo commented on tests/tpostgresunique.nim
> +    check true
I'm not really happy with those check true and check false things. Explicit, meaningful checks are better.

2020-10-25 19:19 UTC, moigagoo commented on tests/tpostgresunique.nim
> +    # Check that test does not reach this point
If the whole proc were just part of the test, there would be no need in this trick.

2020-10-25 19:19 UTC, moigagoo commented on tests/tpostgresunique.nim
> +    # Check test fail with DbError
Unnecessary comment, it's pretty obvious what the check is from the next line.

2020-10-25 19:19 UTC, moigagoo commented on tests/tsqliteunique.nim
> +proc duplicateInsert(dbConn: DbConn)
See comments for Postgres.

2020-10-25 20:20 UTC, Clonkk commented
> What's the point of this forward declaration?

It's mostly habits from developing in C.

2020-10-26 19:35 UTC, moigagoo approved these changes
I'm still not quite happy with some details, but it'll be faster for me to just fix them myself after merge.

2020-10-26 19:35 UTC, merged